### ISSUE TITLE
package `fastdigest` archived on CRAN

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/map#16]
> Archived on 2024-11-11 as issues were not corrected despite reminders.

**Comment by eliotmcintire** [comment]
`fastdigest` is no longer be necessary. It is the same algorithms as `spookyhash` in `digest::digest`, so any use of it can be changed to `digest::digest(algo = "spookyhash")`, (with partial matching) as in here: https://github.com/PredictiveEcology/reproducible/commit/76c7d6ae038c4e42e56e544a8190fa8e86981fd2#diff-67530a3b07655056a0c0ba6a5a8648142b72b02de4785c336fa6a638b6f7b7e5R491

**Comment by achubaty** [comment]
thanks. updated.
